---
language: python
matrix:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11

cache: pip3

install:
# - sudo apt-get update
- sudo apt-get install pandoc
- pip3 install pypandoc
- pip3 install setuptools=="60.8.2"

script:
- make all

before_deploy:
- nvm install 18
- node --version
- npm --version
- npm install
- pip3 install bump2version

deploy:
- provider: script
  script: npm run semantic-release
  skip_cleanup: true
  on:
    python: '3.8'
    branch: main

- provider: pypi
  setuptools_version: "60.8.2"
  user: __token__
  password: $PYPI_TOKEN
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: '3.8'
    tags: true